services:
  - type: web
    name: zlurpbot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
